name: ticket_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  intl: ^0.18.1
  pdf: ^3.10.8
  printing: ^5.12.0
  another_flushbar: ^1.12.30



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/

