// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEOmI6VxycnTyODi0jG_pLX3aCuA-BF0s',
    appId: '1:266373604030:web:f8ea6d50db09c820e474ef',
    messagingSenderId: '266373604030',
    projectId: 'ticket-app-2bf54',
    authDomain: 'ticket-app-2bf54.firebaseapp.com',
    storageBucket: 'ticket-app-2bf54.firebasestorage.app',
    measurementId: 'G-LW34CB356D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmut6gxngJqt3gptcTgBS_fPoN2rNzOK0',
    appId: '1:266373604030:android:e726071aafb0ac72e474ef',
    messagingSenderId: '266373604030',
    projectId: 'ticket-app-2bf54',
    storageBucket: 'ticket-app-2bf54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryR835dN7aauOYIyHSKMMMPeBZF6TNjg',
    appId: '1:266373604030:ios:b826d13ceac39c31e474ef',
    messagingSenderId: '266373604030',
    projectId: 'ticket-app-2bf54',
    storageBucket: 'ticket-app-2bf54.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryR835dN7aauOYIyHSKMMMPeBZF6TNjg',
    appId: '1:266373604030:ios:b826d13ceac39c31e474ef',
    messagingSenderId: '266373604030',
    projectId: 'ticket-app-2bf54',
    storageBucket: 'ticket-app-2bf54.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEOmI6VxycnTyODi0jG_pLX3aCuA-BF0s',
    appId: '1:266373604030:web:6db0ce7e8feceb68e474ef',
    messagingSenderId: '266373604030',
    projectId: 'ticket-app-2bf54',
    authDomain: 'ticket-app-2bf54.firebaseapp.com',
    storageBucket: 'ticket-app-2bf54.firebasestorage.app',
    measurementId: 'G-T8ZBNBWD61',
  );
}
